patterns: [
  {name: look_around,
    waypoints: [
      {frame_id: base_link, target_point: [2.0, 0.0, 0.0], goto_velocity_factor: 0.4, stay_time: 1.0},
      {frame_id: base_link, target_point: [0.0, 2.0, 0.0], goto_velocity_factor: 0.4, stay_time: 1.0},
      {frame_id: base_link, target_point: [0.0, -2.0, 0.0], goto_velocity_factor: 0.4, stay_time: 1.0}
    ]
  },
  {name: look_world,
    waypoints: [
      {frame_id: base_link, target_point: [2.0, 0.0, 0.0], goto_velocity_factor: 0.4, stay_time: 1.0}
    ]
  },
  {name: search_umad,
    waypoints: [
      {frame_id: world, target_point: [0.0, 0.0, 2.5], goto_velocity_factor: 0.4, stay_time: 1.0},
      {frame_id: world, target_point: [0.0, 5.0, 2.5], goto_velocity_factor: 0.4, stay_time: 1.0},
      {frame_id: world, target_point: [7.5, 5.0, 2.5], goto_velocity_factor: 0.4, stay_time: 1.0},
      {frame_id: world, target_point: [7.5, 0.0, 2.5], goto_velocity_factor: 0.4, stay_time: 1.0},
      {frame_id: world, target_point: [7.5, 0.0, 1.0], goto_velocity_factor: 0.4, stay_time: 1.0},
      {frame_id: world, target_point: [7.5, 5.0, 1.0], goto_velocity_factor: 0.4, stay_time: 1.0},
      {frame_id: world, target_point: [0.0, 5.0, 1.0], goto_velocity_factor: 0.4, stay_time: 1.0},
      {frame_id: world, target_point: [0.0, 0.0, 1.0], goto_velocity_factor: 0.4, stay_time: 1.0}
    ]
  },
]
